CREATE TABLE MATERIALS(
MaterialID INT IDENTITY(1,1) PRIMARY KEY,
MaterialName NVARCHAR(255),
FullPiecesByKgOrQuantity INT,
LessPiecesByKgOrQuantity INT
);

CREATE TABLE INVENTORY(
InventoryID INT IDENTITY(1,1) PRIMARY KEY,
MaterialID INT,
CurrentQuantity INT,
FOREIGN KEY (MaterialID) REFERENCES MATERIALS(MaterialID)
);