CREATE TABLE TYPES (
    Type_ID INT PRIMARY KEY,
    Type_Name VARCHAR(50)
);

CREATE TABLE SERVICES (
    Service_ID INT PRIMARY KEY,
    Service_Name VARCHAR(50),
    Price DECIMAL(10,2)
);

CREATE TABLE BOOKING_SERVICES (
    Detail_ID INT PRIMARY KEY,
    Booking_ID INT,
    Service_ID INT,
    Price DECIMAL(10,2),

    FOREIGN KEY (Service_ID) REFERENCES SERVICES(Service_ID),
    FOREIGN KEY (Service_ID) REFERENCES SERVICES(Service_ID)
);